name: Validate Environments

on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: pip install uv

      - name: Validate lockfiles
        run: |
          python scripts/regen_lockfiles.py
          git diff --exit-code || (echo "Lockfiles out of date" && exit 1)